# Generated by Django 5.0.7 on 2024-10-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_emp_empno'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emp',
            name='empno',
            field=models.IntegerField(),
        ),
    ]
