# Generated by Django 5.0.7 on 2024-10-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emp_id_alter_emp_empno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='mgr',
            field=models.IntegerField(),
        ),
    ]
